package pertemuan10;


import static pertemuan10.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author I Putu Eka Saputra
 * TGL : 24 MEI 2025
 */
public class fMahasiswa extends javax.swing.JFrame {
    DefaultTableModel dtm =new DefaultTableModel();

    /**
     * Creates new form fMahasiswa
     * @throws java.sql.SQLException
     */
    public fMahasiswa() throws SQLException {
        initComponents();
        tmhs.setModel(dtm);
        dtm.addColumn("Nama Mahasiswa");
        dtm.addColumn("NIM");
        dtm.addColumn("Prodi");
        dtm.addColumn("Jenis Kelamin");
        
        lsDtMhs();
        fieldEnable(false);
        tombol(false);
        cBaru.setEnabled(true);
        cTutup.setEnabled(true);
        
            
    }
    
    private void fieldEnable(boolean opsi){
        txNIM.setEditable(opsi);
        txNAMA.setEditable(opsi);
        txJK.setEditable(opsi);
        txPRODI.setEditable(opsi);
      }
    
    private void tombol(boolean opsi){
        cBaru.setEnabled(opsi);
        cUbah.setEnabled(opsi);
        cHapus.setEnabled(opsi);
        cTutup.setEnabled(opsi);
    }
    private void clearForm(){
        txNIM.setText("");
        txNAMA.setText("");
        txPRODI.setText("");
        txJK.setText("");
    }
    private void lsDtMhs() throws SQLException{
        Connection cnn = koneksi();
        
        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();
        
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("select * from  mhs;");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                Object[] dta = new Object[4];
                dta[0] = rs.getString("NAMA");
                dta[1] = rs.getString("NIM");
                dta[2] = rs.getString("PRODI");
                dta[3] = rs.getString("JKEL");
                
                dtm.addRow(dta);
            
            }
            cnn.close();
          
        }
    
    }
    private void storeData() throws SQLException{
        Connection cnn  = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("INSERT INTO mhs (NIM,NAMA,PRODI,JKEL) VALUES(?,?,?,?);");
            ps.setString(1,txNIM.getText());
            ps.setString(2,txNAMA.getText());
            ps.setString(3,txPRODI.getText());
            ps.setString(4,txJK.getText());
            ps.executeUpdate();
            cnn.close();
            
        }
    }
    private void updateData() throws SQLException{
        Connection cnn  = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("UPDATE mhs SET NAMA=?,PRODI=?,JKEL=? WHERE NIM=?;");
            
            ps.setString(1,txNAMA.getText());
            ps.setString(2,txPRODI.getText());
            ps.setString(3,txJK.getText());
            ps.setString(4,txNIM.getText());
            ps.executeUpdate();
            cnn.close();
            
        }
    }
    private void destoryData() throws SQLException{
         Connection cnn  = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("DELETE FROM mhs WHERE NIM=?;");
            ps.setString(1,txNIM.getText());
            ps.executeUpdate();
            cnn.close();
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txNIM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNAMA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txJK = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txPRODI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmhs = new javax.swing.JTable();
        cBaru = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("NIM");

        txNIM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nama Mahasiswa");

        txNAMA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        txJK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Program Studi");

        txPRODI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tmhs);

        cBaru.setText("Baru");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txNIM)
                            .addComponent(txPRODI)
                            .addComponent(txJK)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cBaru)
                                        .addGap(18, 18, 18)
                                        .addComponent(cUbah)
                                        .addGap(20, 20, 20)
                                        .addComponent(cHapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(cTutup))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txNAMA))))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPRODI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBaru)
                            .addComponent(cUbah)
                            .addComponent(cHapus)
                            .addComponent(cTutup)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIMActionPerformed
      
    }//GEN-LAST:event_txNIMActionPerformed

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed
         if(cBaru.getText().equals("Baru")){
          cBaru.setText("Simpan");
           cTutup.setText("Batal");
           cUbah.setEnabled(false);
           cHapus.setEnabled(false);
           clearForm();
             fieldEnable(true);
      }else{
             if(!txNIM.getText().equals("")){
                 try { 
                     storeData();
                     lsDtMhs();
                 } catch (SQLException ex) {
                     Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
          cBaru.setText("Baru");
           cTutup.setText("Tutup");
            clearForm();
             fieldEnable(false);
      }
    }//GEN-LAST:event_cBaruActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
        
        if(cUbah.getText().equals("Ubah")) {
            cUbah.setText("Simpan");
            cTutup.setText("Batal");
            
            cBaru.setEnabled(false);
            cHapus.setEnabled(false);
            fieldEnable(true);
            txNIM.setEditable(false);
        
        }else{
            
            try {
                updateData();
                lsDtMhs();
                clearForm();
                 fieldEnable(false);
                 
                 cUbah.setText("Ubah");
                    cTutup.setText("Tutup");
                    cBaru.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            cUbah.setText("Ubah");
            cTutup.setText("Tutup");
            cBaru.setEnabled(true);
            
            
        }
        
    }//GEN-LAST:event_cUbahActionPerformed

    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
        
        int jwb = JOptionPane.showOptionDialog(
                this,
                "Yakin akan menghapus data "+txNIM.getText()+"?",
                "Konfirmasi hapus data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, null, null);
                
        if(jwb == JOptionPane.YES_OPTION){
            try {
                destoryData();
                lsDtMhs();
                clearForm();
                cUbah.setEnabled (false);
                cHapus.setEnabled (false);

            } catch (SQLException ex) {
                Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cHapusActionPerformed

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
        
        if(cTutup.getText ().equals("Tutup")){
        int opsi = JOptionPane.showOptionDialog(this,
                "serius nih bang menutup form ",
                "Tutup Form cuy",
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(opsi == JOptionPane.YES_OPTION){
            System.exit(0);
        } 
        }else{
            cTutup.setText("Tutup");
            cBaru.setText("Baru");
            cUbah.setText("Ubah");
        }
        
        
        
        
    }//GEN-LAST:event_cTutupActionPerformed

    private void tmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmhsMouseClicked
        
        txNAMA.setText( tmhs.getValueAt( tmhs.getSelectedRow() , 0).toString() );
        txNIM.setText( tmhs.getValueAt( tmhs.getSelectedRow() , 1).toString() );
        txPRODI.setText( tmhs.getValueAt( tmhs.getSelectedRow() , 2).toString() );
        String JKx = ( tmhs.getValueAt( tmhs.getSelectedRow() , 3).toString().equals("L")) ?"Laki-laki":"Perempuan";
        txJK.setText (JKx);
        cUbah.setEnabled(true);
        cHapus.setEnabled(true);
        
    }//GEN-LAST:event_tmhsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fMahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tmhs;
    private javax.swing.JTextField txJK;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JTextField txNIM;
    private javax.swing.JTextField txPRODI;
    // End of variables declaration//GEN-END:variables
}
